### ISSUE TITLE
フロントエンドからFastAPIのAPIを呼び出すための修正

### ISSUE THREAD

**Issue by kyuz0216** [team-kentou/server#10]
**概要**
フロントエンドからFastAPIのAPIを呼び出す際に発生するエラーを解消するため、以下の修正を実施する。

1. FastAPIにCORS（オリジン間リソース共有）の設定を追加する。
2. Docker Composeファイルにネットワーク設定を追加する。

**詳細**

### 1. CORSの設定
FastAPIでフロントエンド（例: `http://localhost:3000`）からのリクエストを許可するため、`main.py`に以下のCORS設定を追加する。

```python
from fastapi.middleware.cors import CORSMiddleware

app.add_middleware(
    CORSMiddleware,
    allow_origins=["http://localhost:3000"],  # フロントエンドのURLを指定
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)
```

### 2. Docker Composeファイルのネットワーク設定
フロントエンドとバックエンドを共通ネットワークに所属させるため、Docker Composeファイルに以下の設定を追加する。

#### バックエンド側の修正
`docker-compose.dev.yml`に以下のネットワーク設定を追加する。

```yaml
networks:
  shared-network:
    driver: bridge

services:
  app:
    networks:
      - shared-network

  db:
    networks:
      - shared-network
```

#### フロントエンド側の修正
フロントエンド用の`docker-compose.dev.yml`に以下のネットワーク設定を追加する。

```yaml
networks:
  shared-network:
    external: true

services:
  app:
    networks:
      - shared-network
```

**補足内容・リンク等**
- [FastAPI公式ドキュメント: CORS Middleware](https://fastapi.tiangolo.com/tutorial/cors/)
- [Docker Compose公式ドキュメント: ネットワーク](https://docs.docker.com/compose/networking/)
